name: Build, Test, Publish
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          - goarch: "386"
            goos: darwin 
        #platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out code
      uses: actions/checkout@v2    
    - name: Get go dependencies
      run: go get -v -t -d ./...
    - name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GO111MODULE: on
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        if [ $GOOS = "windows" ]; then export BINARY_SUFFIX="$BINARY_SUFFIX.exe"; fi
        export BINARY_NAME="DnsCompare-$GOOS_$GOARCH$BINARY_SUFFIX"    
        export BINOUT="$PWD/output/$BINARY_NAME"            
        pushd cmd/DnsCompare
        go build -o "$BINOUT"
        popd
    - name: Test
      run: go test ./...
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ !github.head_ref }}
      with:
        name: ${{ matrix.goos }}_${{ matrix.goarch }}
        path: output/